version: '3'

services:
  postgres:
    image: kartoza/postgis:12.0
    container_name: postgres
    environment:
      POSTGRES_PASS: "paodequeijo"
      POSTGRES_USER: "postgres"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql